package org.hbhk.test.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.4
 * Thu Nov 20 15:02:50 CST 2014
 * Generated source version: 2.1.4
 * 
 */
 
@WebService(targetNamespace = "http://webservice.test.hbhk.org/", name = "IHelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://webservice.test.hbhk.org/", className = "org.hbhk.test.webservice.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://webservice.test.hbhk.org/", className = "org.hbhk.test.webservice.GetOrderResponse")
    @WebMethod
    public org.hbhk.test.webservice.Order getOrder();
}
